### ISSUE TITLE
IIOP (GIOP over TCP/IP) support?

### ISSUE THREAD

**Issue by alexchandel** [markandre13/corba.js#1]
First of all this is an awesome project.

I see references to IIOP over regular sockets [here](https://github.com/markandre13/corba.js/blob/master/src/net/socket.ts).  Does this mean corba.js supports talking IIOP (given a suitable TCP socket [like Node's](https://nodejs.org/api/net.html#net_class_net_socket)) to genuine native CORBA servers like omniORB or TAO?

**Comment by markandre13** [comment]
yes. but i don’t intend to cover the whole corba specification. i’m actually testing against omniorb at the moment that at least the parts i implement get it right.

it will also take a while before master is in a shape to publish a new package again.

**Comment by alexchandel** [comment]
Sure, there's a lot of cruft in CORBA.  At the moment, can it connect to omniNames and resolve & talk to a simple, synchronous, bidirectional service?

**Comment by markandre13** [comment]
it can load an ior from a file and initiate a bidirectional connection. there’s no server side yet and the client also can not reinitiate yet, which is a must as omniorb terminates the connection after it’s idle for 30s. the elementary types, sequence, typedef, valuetype, enum are implemented, missing are any, array, union, exception and out and inout. interface objects are only suited for singletons unless one calls release() for each object manually because the code tracks them with a Map instead of a WeakMap.

these tests are green: https://github.com/markandre13/corba.js/blob/master/test/giop.spec.ts

and this is the omniorb counterpart they run against: https://github.com/markandre13/corba.js/blob/master/test/giop/server.cc

while each missing feature is easy to implement, now that the transition to iiop is mostly finished, it’s just that there are so many of them.

**Comment by markandre13** [comment]
oh, and each message must fit into a tcp packet as there’s no code yet to split and combine received data to iiop chunks. that’s less than an hour of work but i don’t need it at the moment.

**Comment by markandre13** [comment]
due to the recent switch from JSON to GIOP, I also began to implement support for:
`orb.stringToObject("corbaname::192.168.1.10#TestService")`
which might be ready in a week or two.
